In [9]:
# Code for Pairwise distances between observations in n-dimensional space.
import numpy as np
from scipy.spatial.distance import pdist , squareform

arrayND = np.array([[1,2,3],[4,5,6],[1,2,3]])

# https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html
#scipy.spatial.distance.pdist

print(squareform(pdist(arrayND,metric='euclidean')))

print(squareform(pdist(arrayND,metric='cosine')))

print(squareform(pdist(arrayND,metric='correlation')))

[[ 0.          5.19615242  0.        ]
 [ 5.19615242  0.          5.19615242]
 [ 0.          5.19615242  0.        ]]
[[ 0.          0.02536815  0.        ]
 [ 0.02536815  0.          0.02536815]
 [ 0.          0.02536815  0.        ]]
[[  0.00000000e+00   2.22044605e-16   2.22044605e-16]
 [  2.22044605e-16   0.00000000e+00   2.22044605e-16]
 [  2.22044605e-16   2.22044605e-16   0.00000000e+00]]
